version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: sunnam1607/yorokorom-frontend:v2
    restart: always
    ports: 
      - "80:3000"
      
