version: "3.8" 

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend  # Mounting backend directory

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend  # Mounting frontend directory
