version: "3.8"

services:
  backend:
    image: yorokorom-backend:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend  # Mounting backend directory

  frontend:
    image: yorokorom-frontend:latest
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend  # Mounting frontend directory
