version: "3.8"

services:
  backend:
    image: sunnam1607/yorokorom-backend:v2
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: sunnam1607/yorokorom-frontend:v2
    restart: always
    ports: 
      - "3000:80"
      
