name: CI/CD

on:
  push:
    branches:
      - main
 
jobs:

  check-path:
    runs-on: ubuntu-latest
    steps:
      - name: Check Path
        run: |
          project_dir=$(find / -type d -name "yorokorom" 2>/dev/null | head -n 1)
      
          if [ -n "$project_dir" ]; then
            cd "$project_dir"
            if [ -f "docker-compose.yml" ]; then
              pwd
               echo "yorokorom list is.............."
              ls -a ./yorokorom
              docker-compose up -d
            else
              echo "Couldn't find 'docker-compose.yml' in the 'yorokorom' directory."
              exit 1
            fi
          else
            echo "Couldn't find the 'yorokorom' directory."
            exit 1
          fi
          


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t your-frontend-image-name:tag .
      
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend
        run: |
          cd backend
          docker build -t your-backend-image-name:tag .

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Deploy
        run: |
      - name: Deploy
        run: |
          project_dir=$(find / -type d -name "yorokorom" 2>/dev/null | head -n 1)
      
          if [ -n "$project_dir" ]; then
            cd "$project_dir"
            if [ -f "docker-compose.yml" ]; then
              pwd
               echo "yorokorom list is.............."
              ls -a ./yorokorom
              docker-compose up -d
            else
              echo "Couldn't find 'docker-compose.yml' in the 'yorokorom' directory."
              exit 1
            fi
          else
            echo "Couldn't find the 'yorokorom' directory."
            exit 1
          fi
