name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t yorokorom-frontend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yorokorom-frontend:latest
          echo "Frontend image built and pushed to Docker Hub as yorokorom-frontend:latest"

      - name: Build and Push Backend Docker Image
        run: |
          cd backend
          docker build -t yorokorom-backend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yorokorom-backend:latest
          echo "Backend image built and pushed to Docker Hub as yorokorom-backend:latest"

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:    
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key:  ${{ secrets.DEV_SERVER_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            docker-compose -f yorokorom/docker-compose.yml pull
            docker-compose -f yorokorom/docker-compose.yml down
            docker-compose -f yorokorom/docker-compose.yml up -d
            echo "Deployment completed."
