name: CI/CD

on:
  push:
    branches:
      - main
 
jobs:

  check-path:
    runs-on: ubuntu-latest
    steps:
      - name: Check Path
        run: |
          project_dir=$(find / -type d -name "yorokorom" 2>/dev/null | head -n 1)
  
          if [ -n "$project_dir" ]; then
            cd "$project_dir"
            pwd
            echo "yorokorom list is.............."
            ls -a
          
            # Check if .dockerignore file exists and show its content
            if [ -f ".dockerignore" ]; then
              echo "Contents of .dockerignore:"
              cat .dockerignore
            else
              echo "No .dockerignore file found in the project."
            fi
          
            # Check the existence of Dockerfile in the backend context
            if [ -f "backend/Dockerfile" ]; then
              echo "Dockerfile found in backend context."
            else
              echo "Dockerfile not found in backend context."
              exit 1
            fi
          
            # Check the existence of Dockerfile in the frontend context
            if [ -f "frontend/Dockerfile" ]; then
              echo "Dockerfile found in frontend context."
            else
              echo "Dockerfile not found in frontend context."
              exit 1
            fi
          else
            echo "Couldn't find the 'yorokorom' directory."
            exit 1
          fi


          


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t your-frontend-image-name:tag .
      
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend
        run: |
          cd backend
          docker build -t your-backend-image-name:tag .

   
