name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t your-frontend-image-name:tag .

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend
        run: |
          cd backend
          docker build -t your-backend-image-name:tag .

  check-path:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Check Path
        run: |
          # Find '/backend' directory and set it as the project directory
          backend_dir=$(find "$(pwd)" -type d -name "backend" 2>/dev/null | head -n 1)

          if [ -n "$backend_dir" ]; then
            cd "$backend_dir"
            pwd
            echo "backend list is.............."
            ls -a

            # Check the existence of Dockerfile in the backend context
            if [ -f "Dockerfile" ]; then
              echo "Dockerfile found in backend context."
              ls -l Dockerfile
              cat Dockerfile
            else
              echo "Dockerfile not found in backend context."
              exit 1
            fi
          else
            echo "Couldn't find the '/backend' directory."
            exit 1
          fi
