name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t sunnam1607/yorokorom-frontend:v2 .
          
          # Docker Hub 로그인 추가
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker push sunnam1607/yorokorom-frontend:v2
          echo "Frontend image built and pushed to Docker Hub as sunnam1607/yorokorom-frontend:v2"

      - name: Build and Push Backend Docker Image
        run: |
          cd backend
          docker build -t sunnam1607/yorokorom-backend:v2 .
          
          # Docker Hub 로그인 추가
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker push sunnam1607/yorokorom-backend:v2
          echo "Backend image built and pushed to Docker Hub as sunnam1607/yorokorom-backend:v2"

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key:  ${{ secrets.DEV_SERVER_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd yorokorom
            echo "Current working directory: $(pwd)"
            ls -la  # 현재 디렉토리 내의 파일 및 디렉토리 목록 출력
            
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
            
            echo "Deployment completed."
