name: CI/CD

on:
  push:
    branches:
      - main
 
jobs:

  check-path:
    runs-on: ubuntu-latest
    steps:
      - name: Check Path
        run: |
          pwd
          ls -a


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t your-frontend-image-name:tag .
      
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend
        run: |
          cd backend
          docker build -t your-backend-image-name:tag .

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Deploy
        run: |
          pwd
          ls -a
          
