name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t yorokorom-frontend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yorokorom-frontend:latest
          echo "Frontend image built and pushed to Docker Hub as yorokorom-frontend:latest"

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend and Push Docker Image
        run: |
          cd backend
          docker build -t yorokorom-backend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yorokorom-backend:latest
          echo "Backend image built and pushed to Docker Hub as yorokorom-backend:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:    
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key:  ${{ secrets.DEV_SERVER_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            docker pull yorokorom-backend:latest
            docker stop yorokorom-backend-container || true
            docker rm yorokorom-backend-container || true
            docker run -d -p 8080:8080 --name yorokorom-backend-container yorokorom-backend:latest

            docker pull yorokorom-frontend:latest
            docker stop yorokorom-frontend-container || true
            docker rm yorokorom-frontend-container || true
            docker run -d -p 3000:80 --name yorokorom-frontend-container yorokorom-frontend:latest
